### ISSUE TITLE
Specify version of FONA this is meant to extend

### ISSUE THREAD

**Issue by nabeel-halo** [botletics/Botletics-SIM7000#4]
I see this library is still in development but I was excited to give it a try. I installed it to Arduino IDE and also installed latest FONA (1.3.11), but it results in a ton of mismatching overload definitions between the two libraries. I also tried other versions of FONA but was unable to find a version that worked.

Sample compilation errors (there are many):

```
/home/nabeel/Arduino/libraries/Botletics-SIM7000-main/src/BotleticsSIM7000.cpp:3665:9: error: prototype for 'boolean Adafruit_FONA::sendCheckReply(const char*, FONAFlashStringPtr, uint16_t)' does not match any in class 'Adafruit_FONA'
 boolean Adafruit_FONA::sendCheckReply(const char* send, FONAFlashStringPtr reply, uint16_t timeout) {
         ^~~~~~~~~~~~~
```

This being I assume because that overload doesn't exist for sendCheckReply and a new overload (or any definition) cannot occur outside of the class definition.

How can I properly compile this library?

**Comment by botletics** [comment]
Sorry, version 1.0.1 compiles, but right now only 1.0.0 shows up in the Arduino library manager.

**Comment by botletics** [comment]
Sorry for the confusion! This library was just ported over to meet the Arduino library manager guidelines. Release 1.0.0 actually had a compile error, but you should be able to find and install 1.0.1 with the Arduino library manager soon.

**Comment by botletics** [comment]
Release 1.0.3 fixes the compiler errors. Please check now!

**Comment by nabeel-halo** [comment]
Thank you! I can confirm it compiles and runs perfectly. Please also consider uploading this library to the [PlatformIO Library Registry](https://docs.platformio.org/en/latest/librarymanager/creating.html#publishing). They fully support Arduino libraries (the library.json spec is recommended, but library.properties is accepted), so there would be no changes needed. PlatformIO is a [widely used](https://github.com/platformio/platformio-core) "more serious" alternative to the Arduino IDE!
Thanks again!
